### ISSUE TITLE
When we click the links, the page not upload.

### ISSUE THREAD

**Issue by jordibrus** [ColdTrick/file_tools#52] opened 2015-04-09 14:19 UTC
I need to have the line 414 on file file_tools/lib/hooks.php like this to upload the links:
`$returnvalue = "file/group/" . $container->getGUID() . "/#" . $entity->getGUID();`
The problem is that it does not work with either the sidebar and the breadcrumbs

**Comment by jdalsem** [comment] 2015-12-11 11:06
I am closing this issue as i am unable to reproduce this. If you have more information and steps to reproduce this let me know

**Closed by jdalsem** 2015-12-11 11:06 UTC
